# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: cc

  bin_paths:
    - <%= Rails.root %>/vendor/bundle/bin

  services:
  - name: etcd-dedicated-bosh-lite
    deployment_name_prefix: etcd
    id: b9698740-4810-4dc5-8da6-54581f5108c4
    description: "etcd: A highly-available key value store for shared configuration and service discovery"
    tags:
      - etcd
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: A highly-available key value store for shared configuration and service discovery.
        long_description: A highly-available key value store for shared configuration and service discovery. High-availablity clusters are available.
    bosh:
      target: https://192.168.50.4:25555
      username: admin
      password: admin
      dns_root: ~
      infrastructure: warden
      # director_uuid: - calculated after login
      # cpi: - cpi calculated after login (warden, openstack)
      releases:
      - name: etcd
        version: 2
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/templates
        templates:
         - etcd-deployment.yml
         - etcd-jobs.yml
         - etcd-properties.yml
         - etcd-infrastructure-warden.yml
      binding_config:
        master_host_job_name: etcd_leader_z1
    plans:
    - name: 1-server
      id: 6e8ece8c-4fe6-4d58-9aeb-497d6aeba113
      description: Etcd running on a single dedicated server
      metadata:
        cluster_size: 1
        cost: 100
        bullets:
        - content: Etcd server
        - content: Single small server
        - content: Development-only, no high-availability
    - name: 3-servers
      id: 1a448d0e-bc54-4a16-8d2f-ab701be20c40
      description: Etcd running across three dedicated servers
      metadata:
        cluster_size: 3
        cost: 300
        bullets:
        - content: Etcd servers
        - content: 3 small servers
        - content: High availability, leader election
    - name: 5-servers
      id: 5cfa57fc-1474-4eb9-9afb
      description: Etcd running across five dedicated servers
      metadata:
        cluster_size: 5
        cost: 500
        bullets:
        - content: Etcd servers
        - content: 3 small servers
        - content: High availability, leader election

development:
  auth_password: 'secret'
  etcd:
    host: 127.0.0.1
    port: 5200

  extra_deployment_name_prefix: ~

  <<: *defaults

test:
  auth_password: 'secret'
  etcd:
    host: 127.0.0.1
    port: 6200

  extra_deployment_name_prefix: test
  <<: *defaults
