# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  tmp_path: '<%= Rails.root %>/tmp'

  auth_username: cc

  bin_paths:
    - <%= Rails.root %>/vendor/bundle/bin

  available_boshes:
    - target: https://192.168.50.4:25555
      username: admin
      password: admin
      dns_root: ~
      cpi_infrastructure: warden
      # director_uuid: - calculated after login
      # cpi: - cpi calculated after login (warden, openstack)
      infrastructure_networks:
        - ip_range_start: 10.244.2.0
          template: <%= Rails.root %>/infrastructure_pools/warden/10.244.2.0.yml
        - ip_range_start: 10.244.2.40
          template: <%= Rails.root %>/infrastructure_pools/warden/10.244.2.40.yml
        - ip_range_start: 10.244.2.80
          template: <%= Rails.root %>/infrastructure_pools/warden/10.244.2.80.yml
<% if ENV['BOSH_AWS_EC2_TARGET'] %>
    - target: <%= ENV['BOSH_AWS_EC2_TARGET'] %>
      username: admin
      password: admin
      dns_root: ~
      cpi_infrastructure: aws-ec2
      # director_uuid: - calculated after login
      # cpi: - cpi calculated after login (warden, openstack)
<% end %>
<% if ENV['BOSH_GOOGLE_TARGET'] %>
    - target: <%= ENV['BOSH_GOOGLE_TARGET'] %>
      username: admin
      password: admin
      dns_root: ~
      cpi_infrastructure: google
      # director_uuid: - calculated after login
      # cpi: - cpi calculated after login (warden, openstack)
<% end %>

  services:
  - name: etcd-dedicated-bosh-lite
    deployment_name_prefix: etcd
    id: b9698740-4810-4dc5-8da6-54581f5108c4
    description: "etcd: A highly-available key value store for shared configuration and service discovery"
    tags:
      - etcd
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: A highly-available key value store for shared configuration and service discovery.
        long_description: A highly-available key value store for shared configuration and service discovery. High-availablity clusters are available.
    default_credentials:
      port: 4001
    detect_credentials:
      - name: host
        class: BindingAttributes::JobIpAddress
        attributes:
          job_name: etcd_leader_z1
    bosh_target: https://192.168.50.4:25555
    bosh_release:
      releases:
      - name: etcd
        version: 3
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/etcd/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-warden.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-warden.yml
    plans:
    - name: 1-server
      id: 6e8ece8c-4fe6-4d58-9aeb-497d6aeba113
      description: Etcd running on a single dedicated server
      metadata:
        cost: 100
        bullets:
        - content: Etcd server
        - content: Single small server
        - content: Development-only, no high-availability
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 0
    - name: 3-servers
      id: 1a448d0e-bc54-4a16-8d2f-ab701be20c40
      description: Etcd running across three dedicated servers
      metadata:
        cost: 300
        bullets:
        - content: Etcd servers
        - content: 3 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 2
    - name: 5-servers
      id: 5cfa57fc-1474-4eb9-9afb
      description: Etcd running across five dedicated servers
      metadata:
        cost: 500
        bullets:
        - content: Etcd servers
        - content: 5 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 4

  - name: datastax-cassandra-dedicated-bosh-lite
    deployment_name_prefix: cassandra
    id: 4d1cab61-09ff-4442-a8e7-d270459bd025
    description: "Datastax Cassandra: is the right choice when you need scalability and high availability without compromising performance"
    tags:
      - cassandra
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: The right choice when you need scalability and high availability without compromising performance
        long_description: "The DataStax Cassandra database is the right choice when you need scalability and high availability without compromising performance. Linear scalability and proven fault-tolerance on commodity hardware or cloud infrastructure make it the perfect platform for mission-critical data. Cassandra's support for replicating across multiple datacenters is best-in-class, providing lower latency for your users and the peace of mind of knowing that you can survive regional outages."
    default_credentials:
      port: 7000
    detect_credentials:
      - name: host
        class: BindingAttributes::JobsIpAddresses
        attributes:
          job_names:
            - datastax_cassandra_seed_z1
            - datastax_cassandra_z1
    bosh_target: https://192.168.50.4:25555
    bosh_release:
      releases:
      - name: datastax_cassandra
        version: 1
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/datastax_cassandra/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-warden.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-warden.yml
    plans:
    - name: 3-servers
      id: 4ca347c2-f4da-4d76-8536-f7e0b589c8a2
      description: Cassandra running across three dedicated servers
      metadata:
        cost: 300
        bullets:
        - content: Cassandra servers
        - content: 3 small servers
        - content: High availability
      bosh_deployment_stub:
        jobs:
          - name: cassandra_z1
            instances: 2
    - name: 5-servers
      id: 069f3fd0-560d-43a5-840d-3b8aca9e63c2
      description: Cassandra running across five dedicated servers
      metadata:
        cost: 500
        bullets:
        - content: Cassandra servers
        - content: 5 small servers
        - content: High availability
      bosh_deployment_stub:
        jobs:
          - name: datastax_cassandra_z1
            instances: 4

  - name: redis-dedicated-bosh-lite
    deployment_name_prefix: redis
    id: 1683fe81-b492-4e92-8282-0cdca7c316e1
    description: "redis: An advanced key-value store, can contain strings, hashes, lists, sets and sorted sets."
    tags:
      - redis
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: An advanced key-value store, can contain strings, hashes, lists, sets and sorted sets.
        long_description: Redis is an open source, BSD licensed, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets. High-availablity clusters are available.
    default_credentials:
      port: 6379
    detect_credentials:
      - name: host
        class: BindingAttributes::JobIpAddress
        attributes:
          job_name: redis_leader_z1
    bosh_target: https://192.168.50.4:25555
    bosh_release:
      releases:
      - name: redis
        version: 3
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/redis/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-warden.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-warden.yml
    plans:
    - name: 1-server
      id: f643f60d-7e5e-4fbf-934f-c089ed2f2720
      description: Redis running on a single dedicated server
      metadata:
        cluster_size: 1
        cost: 100
        bullets:
        - content: Redis server
        - content: Single small server
        - content: Development-only, no high-availability
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 0
    - name: 2-servers
      id: e23b4ad6-d33f-4764-803b-d507bb0b95d1
      description: Redis running across two dedicated servers
      metadata:
        cluster_size: 2
        cost: 200
        bullets:
        - content: Redis servers
        - content: 2 small servers
        - content: High availability, master-slave
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 1
    - name: 3-servers
      id: 1a6ee012-a591-4d7f-99ae-7ff4af1e240a
      description: Redis running across three dedicated servers
      metadata:
        cluster_size: 3
        cost: 300
        bullets:
        - content: Redis servers
        - content: 3 small servers
        - content: High availability, master-slave
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 2

<% if ENV['BOSH_AWS_EC2_TARGET'] %>
  - name: etcd-dedicated-aws-ec2
    deployment_name_prefix: etcd
    id: d12daff6-6a2d-4d38-86cd-9ba5125f576d
    description: "etcd: A highly-available key value store for shared configuration and service discovery, running on AWS EC2"
    tags:
      - etcd
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: A highly-available key value store for shared configuration and service discovery.
        long_description: A highly-available key value store for shared configuration and service discovery. High-availablity clusters are available.
    default_credentials:
      port: 4001
    detect_credentials:
      - name: host
        class: BindingAttributes::JobIpAddress
        attributes:
          job_name: etcd_leader_z1
    bosh_target: <%= ENV['BOSH_AWS_EC2_TARGET'] %>
    bosh_release:
      releases:
      - name: etcd
        version: 3
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/etcd/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-aws-ec2.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-aws-ec2.yml
    plans:
    - name: 1-server
      id: db55e7ed-cb0f-4573-9111-4cd4833bb7e7
      description: Etcd running on a single dedicated server
      metadata:
        cost: 100
        bullets:
        - content: Etcd server
        - content: Single small server
        - content: Development-only, no high-availability
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 0
    - name: 3-servers
      id: 38ee66f4-5d95-42ed-992b-50181a77f481
      description: Etcd running across three dedicated servers
      metadata:
        cost: 300
        bullets:
        - content: Etcd servers
        - content: 3 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 2
    - name: 5-servers
      id: bfdd7042-ca2b-43b5-af1c-e252c10dce9d
      description: Etcd running across five dedicated servers
      metadata:
        cost: 500
        bullets:
        - content: Etcd servers
        - content: 5 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 4
<% end %>

<% if ENV['BOSH_GOOGLE_TARGET'] %>
  - name: etcd-dedicated-google
    deployment_name_prefix: etcd
    id: 44f5aa33-4b0c-455d-bc8e-792bf76a6f0b
    description: "etcd: A highly-available key value store for shared configuration and service discovery, running on Google Compute"
    tags:
      - etcd
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: A highly-available key value store for shared configuration and service discovery.
        long_description: A highly-available key value store for shared configuration and service discovery. High-availablity clusters are available.
    default_credentials:
      port: 4001
    detect_credentials:
      - name: host
        class: BindingAttributes::JobIpAddress
        attributes:
          job_name: etcd_leader_z1
    bosh_target: <%= ENV['BOSH_GOOGLE_TARGET'] %>
    bosh_release:
      releases:
      - name: etcd
        version: 3
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/etcd/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-google.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-google.yml
    plans:
    - name: 1-server
      id: 1378796c-a16f-444d-bdd5-95c12a045c6b
      description: Etcd running on a single dedicated server
      metadata:
        cost: 100
        bullets:
        - content: Etcd server
        - content: Single small server
        - content: Development-only, no high-availability
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 0
    - name: 3-servers
      id: d80ff8f3-7d6b-426a-8ed4-7f7acb6e9bc4
      description: Etcd running across three dedicated servers
      metadata:
        cost: 300
        bullets:
        - content: Etcd servers
        - content: 3 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 2
    - name: 5-servers
      id: 83db3858-2fe1-4b17-bcb5-71d1573b829b
      description: Etcd running across five dedicated servers
      metadata:
        cost: 500
        bullets:
        - content: Etcd servers
        - content: 5 small servers
        - content: High availability, leader election
      bosh_deployment_stub:
        jobs:
          - name: etcd_z1
            instances: 4

  - name: redis-dedicated-google
    deployment_name_prefix: redis
    id: 0eb96de7-bb26-4b65-8384-a804e982ebf6
    description: "redis: An advanced key-value store, can contain strings, hashes, lists, sets and sorted sets, on Google Compute"
    tags:
      - redis
      - nosql
    metadata:
      provider:
        name: "Stark & Wayne LLC"
      listing:
        imageUrl: ~
        blurb: An advanced key-value store, can contain strings, hashes, lists, sets and sorted sets.
        long_description: Redis is an open source, BSD licensed, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets. High-availablity clusters are available.
    default_credentials:
      port: 6379
    detect_credentials:
      - name: host
        class: BindingAttributes::JobIpAddress
        attributes:
          job_name: redis_leader_z1
    bosh_target: <%= ENV['BOSH_GOOGLE_TARGET'] %>
    bosh_release:
      releases:
      - name: redis
        version: 3
        url: ~
      release_templates:
        base_path: <%= Rails.root %>/releases/redis/templates
        deployment_stub: stub.yml
        infrastructure_stub: infrastructure-google.yml
        templates:
         - deployment.yml
         - jobs.yml
         - properties.yml
         - infrastructure-google.yml
    plans:
    - name: 1-server
      id: 7e8b7461-e79e-4138-b378-9b4cf9cac4a4
      description: Redis running on a single dedicated server
      metadata:
        cluster_size: 1
        cost: 100
        bullets:
        - content: Redis server
        - content: Single small server
        - content: Development-only, no high-availability
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 0
    - name: 2-servers
      id: 07145760-6d44-495e-9bd9-d74d9e80771e
      description: Redis running across two dedicated servers
      metadata:
        cluster_size: 2
        cost: 200
        bullets:
        - content: Redis servers
        - content: 2 small servers
        - content: High availability, master-slave
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 1
    - name: 3-servers
      id: a7f6cc90-d76c-4b7c-99e0-0987cb2875b2
      description: Redis running across three dedicated servers
      metadata:
        cluster_size: 3
        cost: 300
        bullets:
        - content: Redis servers
        - content: 3 small servers
        - content: High availability, master-slave
      bosh_deployment_stub:
        jobs:
          - name: redis_z1
            instances: 2
<% end %>

development:
  auth_password: 'secret'
  etcd:
    host: 127.0.0.1
    port: 5100

  extra_deployment_name_prefix: ~

  base_url: http://servaas.ngrok.com

  <<: *defaults

test:
  auth_password: 'secret'
  etcd:
    host: 127.0.0.1
    port: 6100

  extra_deployment_name_prefix: test

  base_url: http://127.0.0.1:6000

  <<: *defaults
