meta:
  environment: redis-aws

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: redis_leader_z1
    instances: 1
    networks:
      - name: redis1
        static_ips: ~
  - name: redis_z1
    instances: 2
    networks:
      - name: redis1
        static_ips: ~
    properties:
      redis:
        master: (( "0.redis-leader-z1.redis1." meta.environment ".microbosh" ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: redis1
    type: dynamic
    cloud_properties:
      security_groups:
        - default
