meta:
  environment: etcd-warden

  stemcell:
    name: bosh-stemcell
    version: 993

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: etcd_leader_z1
    instances: 1
    networks:
      - name: etcd1
        static_ips: (( static_ips(0) ))
  - name: etcd_z1
    instances: 2
    networks:
      - name: etcd1
        static_ips: ~
    properties:
      etcd:
        leader_address: (( jobs.etcd_leader_z1.networks.etcd1.static_ips.[0] ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: etcd1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2

  - cloud_properties:
      name: random
    range: 10.244.3.28/30
    reserved:
    - 10.244.3.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.40/30
    reserved:
    - 10.244.3.41
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.44/30
    reserved:
    - 10.244.3.45
    static: []
